apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-configmap
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS user(
      id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
      email VARCHAR(255) NOT NULL UNIQUE,
      password VARCHAR(255) NOT NULL
    );

    INSERT INTO user (email, password) VALUES ('maloong@gmail.com','Admin123')
